name: developpement-test.yml

permissions:
    contents: read

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false #Permet de continuer les tests sur d'autres versions même si ça plante dans une
            matrix: #Permet de gérer plusieurs versions PHP ou autres options multiples
                php-version: ['8.2', '8.3']

        services:
            database:
                image: postgres:16
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: ina_zaoui_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready"
                    --health-interval 10s
                    --health-timeout 6s
                    --health-retries 5

        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

            - name: Installer PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: pdo_pgsql, intl
                  coverage: none

            - name: Installer les dépendances
              run: composer install --prefer-dist --no-progress

            - name: Lancement des tests
              run: composer test-ci
              env:
                DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/ina_zaoui_test?serverVersion=16&charset=utf8"
